---
# tasks file for observium-agent
- name: be sure xinetd is installed
  apt:  pkg=xinetd state=installed
  tags: xinetd
  when: ansible_distribution == "Debian" OR ansible_distribution == "Ubuntu"

- name: be sure xinetd is installed
  yum:  pkg=xinetd state=installed
  tags: xinetd
  when: ansible_distribution == "CentOS"

- template: src=observium_agent_xinetd dest=/etc/xinetd.d/observium_agent_xinetd owner=root group=root mode=0644
  notify: restart xinetd
  tags:
  - xinetd
    
- name: deploy observium agent script
  template: src=observium_agent dest=/usr/bin/observium_agent owner=root group=root mode=0655
    
- name: enable xinetd
  service: name=xinetd state=started
  tags: xinetd

- name: deploy observium distro script
  template: src=distro dest=/usr/bin/distro owner=root group=root mode=0655

- lineinfile: dest=/etc/snmp/snmpd.conf line="#This line allows Observium to detect the host OS if the distro script is installed"
- lineinfile: dest=/etc/snmp/snmpd.conf line="extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro"  
  notify: restart snmpd

- file: path=/usr/lib/observium_agent/local state=directory mode=0755

- template: src=local-agents/dpkg dest=/usr/lib/observium_agent/local/dpkg owner=root group=root mode=0655  
  when: ansible_distribution == "Debian"

- include: tasks/apache.yml
  when: obs_agent_apache_enable == true

- include: tasks/pg.yml
  when: obs_agent_pg_enable == true

- include: tasks/bind.yml
  when: obs_agent_bind_enable == true
